packages:
  - docs
  - playground
  - packages/**
  - examples/**
catalog:
  '@antfu/ni': ^24.3.0
  '@xiaohe01/eslint-config': ^1.5.1
  bumpp: ^10.1.0
  eslint: ^9.26.0
onlyBuiltDependencies:
  - unrs-resolver