packages:
  - docs
  - playground
  - packages/**
  - examples/**
catalog:
  '@antfu/ni': ^25.0.0
  '@xiaohe01/eslint-config': ^1.8.0
  bumpp: ^10.2.0
  eslint: ^9.29.0
onlyBuiltDependencies:
  - unrs-resolver